apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: gateway-ns
spec:
    accessModes:
      - ReadWriteOnce
    storageClassName: retail-sc
    resources:
      requests:
        storage: 2Gi
